name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_BACKEND_SERVICE_ID: ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
          RENDER_FRONTEND_SERVICE_ID: ${{ secrets.RENDER_FRONTEND_SERVICE_ID }}
        run: |
          # Backend deploy
          curl -X POST -H "Authorization: Bearer $RENDER_API_KEY" https://api.render.com/deploy/srv-$RENDER_BACKEND_SERVICE_ID
          # Frontend deploy
          curl -X POST -H "Authorization: Bearer $RENDER_API_KEY" https://api.render.com/deploy/srv-$RENDER_FRONTEND_SERVICE_ID
